from typing import Protocol

from dagster_project.core.discussions.shared_models import DiscussionLink, ExtractionResult


class DiscussionPlatformHandler(Protocol):
    @classmethod
    def platform_name(cls) -> str: ...

    @classmethod
    def can_handle(cls, url: str) -> bool: ...

    async def extract_article_url(self, aggregator_url: str) -> ExtractionResult: ...

    async def search_by_url(self, url: str) -> list[str]: ...

    async def fetch_story(self, discussion_url: str, story_id: str | int | None = None): ...

    def extract_story_id(self, discussion_url: str) -> str | int: ...

    def build_discussion_link(self, story_id: str | int) -> DiscussionLink: ...
