"""create todos table

Revision ID: 6c8b5aea510d
Revises:
Create Date: 2025-10-19 01:29:05.649391

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6c8b5aea510d"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "todos",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("completed", sa.Boolean(), nullable=False),
        sa.Column(
            "priority",
            sa.Enum("LOW", "MEDIUM", "HIGH", name="priorityenum"),
            nullable=False,
        ),
        sa.Column("due_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_todos_completed"), "todos", ["completed"], unique=False)
    op.create_index("ix_todos_completed_due_date", "todos", ["completed", "due_date"], unique=False)
    op.create_index(op.f("ix_todos_due_date"), "todos", ["due_date"], unique=False)
    op.create_index(op.f("ix_todos_priority"), "todos", ["priority"], unique=False)
    op.create_index(op.f("ix_todos_title"), "todos", ["title"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_todos_title"), table_name="todos")
    op.drop_index(op.f("ix_todos_priority"), table_name="todos")
    op.drop_index(op.f("ix_todos_due_date"), table_name="todos")
    op.drop_index("ix_todos_completed_due_date", table_name="todos")
    op.drop_index(op.f("ix_todos_completed"), table_name="todos")
    op.drop_table("todos")
    # ### end Alembic commands ###
